#PBS -q preemptable
#PBS -A EVITA
#PBS -l walltime=01:00:00
#PBS -l select=2:system=polaris:ncpus=64:ngpus=4
#PBS -l filesystems=home:grand
#PBS -l place=scatter
#PBS -j oe
#PBS -N agentic_chain_dbg

source /grand/EVITA/erik/envs/agentic/bin/activate

export NCCL_NET_GDR_LEVEL=PHB
export NCCL_CROSS_NIC=1
export NCCL_COLLNET_ENABLE=1
export NCCL_NET="AWS Libfabric"
export LD_LIBRARY_PATH=/soft/libraries/aws-ofi-nccl/v1.9.1-aws/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/soft/libraries/hwloc/lib/:$LD_LIBRARY_PATH
export FI_CXI_DISABLE_HOST_REGISTER=1
export FI_MR_CACHE_MONITOR=userfaultfd
export FI_CXI_DEFAULT_CQ_SIZE=131072

cd $PBS_O_WORKDIR

MASTER_ADDR=$(head -n 1 $PBS_NODEFILE)
export MASTER_ADDR
export MASTER_PORT=29500
echo "Master node: $MASTER_ADDR Master port: $MASTER_PORT"

#accelerate launch --main_process_ip $MASTER_ADDR --main_process_port $MASTER_PORT --config_file accelerate_config.yaml gemma_multinode.py

torchrun \
  --nnodes=2 \
  --nproc_per_node=4 \
  --rdzv_backend=c10d \
  --rdzv_endpoint=${MASTER_ADDR}:${MASTER_PORT} \
  gemma_multinode.py
